import * as React from 'react';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';

export default function AddDetails({opens, business_code,cust_number,clear_date,buisness_year,doc_id,posting_date,document_create_date,due_in_date,invoice_currency,document_type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,changeHandler,submitHandler,handleCloses}){
  return (
    <div>
    <Dialog opens={opens} onClose={handleCloses}>
    <DialogTitle>Add</DialogTitle>
    <DialogContent>
          <TextField
            autoFocus
            name="business_code"
            margin="dense"
            id="business_code"
            label="business_code"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={business_code}
            variant="standard"
          />
          <TextField
            autoFocus
            name="cust_number"
            margin="dense"
            id="cust_number"
            label="cust_number"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={cust_number}
            variant="standard"
          />
          <TextField
            autoFocus
            name="clear_date"
            margin="dense"
            id="clear_date"
            label="clear_date"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={clear_date}
            variant="standard"
          />
          <TextField
            autoFocus
            name="buisness_year"
            margin="dense"
            id="buisness_year"
            label="buisness_year"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={buisness_year}
            variant="standard"
          />
          <TextField
            autoFocus
            name="doc_id"
            margin="dense"
            id="doc_id"
            label="doc_id"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={doc_id}
            variant="standard"
          />
          <TextField
            autoFocus
            name="posting_date"
            margin="dense"
            id="posting_date"
            label="posting_date"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={posting_date}
            variant="standard"
          />
          <TextField
            autoFocus
            name="document_create_date"
            margin="dense"
            id="document_create_date"
            label="document_create_date"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={document_create_date}
            variant="standard"
          />
          
          <TextField
            autoFocus
            name="due_in_date"
            margin="dense"
            id="due_in_date"
            label="due_in_date"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={due_in_date}
            variant="standard"
          />
          <TextField
            autoFocus
            name="invoice_currency"
            margin="dense"
            id="invoice_currency"
            label="invoice_currency"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={invoice_currency}
            variant="standard"
          />
          <TextField
            autoFocus
            name="document_type"
            margin="dense"
            id="document_type"
            label="document_type"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={document_type}
            variant="standard"
          />
          <TextField
            autoFocus
            name="posting_id"
            margin="dense"
            id="posting_id"
            label="posting_id"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={posting_id}
            variant="standard"
          />
          
          <TextField
            autoFocus
            name="total_open_amount"
            margin="dense"
            id="total_open_amount"
            label="total_open_amount"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={total_open_amount}
            variant="standard"
          />
          <TextField
            autoFocus
            name="baseline_create_date"
            margin="dense"
            id="baseline_create_date"
            label="baseline_create_date"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={baseline_create_date}
            variant="standard"
          />
          <TextField
            autoFocus
            name="cust_payment_terms"
            margin="dense"
            id="cust_payment_terms"
            label="cust_payment_terms"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={cust_payment_terms}
            variant="standard"
          />
          <TextField
            autoFocus
            name="invoice_id"
            margin="dense"
            id="invoice_id"
            label="invoice_id"
            type="text"
            fullWidth
            onChange={changeHandler}
            value={invoice_id}
            variant="standard"
          />
          </DialogContent>
          <DialogActions>
          <Button onClick={() => handleCloses(false)}>Cancel</Button>
          <Button onClick={() => {
          handleCloses(true);
          submitHandler();
        }}>Add</Button>
        </DialogActions>
    </Dialog>
  </div>
  );
}
